spring:
  application:
    name: collector-service
  config:
    import: "configserver:"
  cloud:
    config:
      name: collector-service
      discovery:
        enabled: true
        service-id: config-server
      retry:
        use-random-policy: true
        max-interval: 6000
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.instance.port:8761}/eureka