server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://event-db:5432/eventdb
    username: dbuser
    password: 12345

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
    leaseRenewalIntervalInSeconds: 10

stats:
  service:
    id: stats-server

grpc:
  client:
    collector-service:
      address: discovery:///collector-service
      negotiationType: plaintext
    analyzer-service:
      address: discovery:///analyzer-service
      negotiationType: plaintext

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

resilience4j:
  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 300ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.RetryableException
          - feign.FeignException
          - java.io.IOException
      request-service:
        max-attempts: 3
        wait-duration: 300ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.RetryableException
          - feign.FeignException
          - java.io.IOException