server:
  port: 0

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: stats-aggregator
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: ru.yandex.practicum.stats.avro.UserActionAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: ru.yandex.practicum.stats.avro.SpecificRecordAvroSerializer

stats:
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1
  actions:
    view: 1.0
    register: 2.0
    like: 3.0

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
    leaseRenewalIntervalInSeconds: 10